dist: trusty
sudo: false
language: cpp
addons:
  apt:
    packages:
      - libflint-dev
script:
  - find /usr -name '*flint*'
  - export CPLUS_INCLUDE_PATH="$(pwd)":"/usr/include":"/usr/include/flint":"/usr/local/include":"/usr/local/include/flint":${CPLUS_INCLUDE_PATH}
  - g++ ./test/pe_test.c -o ./a.out --std=c++11 -fopenmp -DTEST_ALL -DENABLE_ASSERT=0 -DTRY_TO_USE_INT128=0 -DENABLE_OPENMP=1 -DENABLE_EIGEN=0 -DENABLE_GMP=1 -DENABLE_FLINT=1 -DENABLE_MPFR=1 -DENABLE_MPIR=1 -DENABLE_LIBBF=0
