dist: trusty
sudo: reqquired
language: cpp
script:
  - sudo apt-get update
  - sudo apt-get -y install libgmp-dev
  - export CPLUS_INCLUDE_PATH="$(pwd)":"/usr/include":${CPLUS_INCLUDE_PATH}
  - export LIBRARY_PATH="/usr/lib":${LIBRARY_PATH}
  - g++ ./test/pe_test.c -o ./a.out --std=c++11 -O3 -march=native -mtune=native -fopenmp -lgmpxx -lgmp -DTEST_ALL -DENABLE_ASSERT=0 -DTRY_TO_USE_INT128=1 -DENABLE_OPENMP=1 -DENABLE_EIGEN=0 -DENABLE_GMP=1 -DENABLE_FLINT=0 -DENABLE_MPFR=0 -DENABLE_MPIR=0 -DENABLE_LIBBF=0
