dist: bionic
sudo: reqquired
language: cpp
script:
  - sudo apt-get update
  - sudo apt-get -y install libgmp-dev
  - sudo apt-get -y install libflint-dev
  - sudo apt-get -y install libntl-dev
  - export CPLUS_INCLUDE_PATH="$(pwd)":"/usr/include/flint":${CPLUS_INCLUDE_PATH}
  - export LIBRARY_PATH="/usr/lib":${LIBRARY_PATH}
  - g++ ./test/pe_test.c -o ./b.out --std=c++14 -O3 -march=native -mtune=native -fopenmp -lgmpxx -lflint -lntl -lgmp -DTEST_ALL -DCONTINUOUS_INTEGRATION_TEST -DENABLE_ASSERT=0 -DTRY_TO_USE_INT128=1 -DENABLE_OPENMP=1 -DENABLE_EIGEN=0 -DENABLE_GMP=1 -DENABLE_FLINT=1 -DENABLE_MPFR=1 -DENABLE_NTL=1 -DENABLE_LIBBF=0 && ./b.out
