dist: trusty
sudo: false
language: cpp
script:
  - export CPLUS_INCLUDE_PATH="$(pwd)":${CPLUS_INCLUDE_PATH}
  - g++ ./test/pe_test.c -o ./a.out --std=c++11 -march=x86-64 -fopenmp -DTEST_ALL -DENABLE_ASSERT=0 -DTRY_TO_USE_INT128=1 -DENABLE_OPENMP=1 -DENABLE_EIGEN=0 -DENABLE_GMP=0 -DENABLE_FLINT=0 -DENABLE_MPFR=0 -DENABLE_MPIR=0 -DENABLE_LIBBF=0
