dist: trusty
sudo: reqquired
language: cpp
script:
  - sudo apt-get update
  - apt-get -y install libflint-dev
  - export CPLUS_INCLUDE_PATH="$(pwd)":"/usr/include":"/usr/include/FLINT":${CPLUS_INCLUDE_PATH}
  - export LIBRARY_PATH="/usr/lib":${LIBRARY_PATH}
  - g++ ./test/pe_test.c -o ./a.out --std=c++11 -fopenmp -lgmpxx -lflint -lgmp -lmpfr -lmpir -DTEST_ALL -DENABLE_ASSERT=0 -DTRY_TO_USE_INT128=0 -DENABLE_OPENMP=1 -DENABLE_EIGEN=0 -DENABLE_GMP=1 -DENABLE_FLINT=1 -DENABLE_MPFR=1 -DENABLE_MPIR=1 -DENABLE_LIBBF=0
